name: Tradingview Scraper

on:
  push:
    branches: [ main ]
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas openpyxl selenium webdriver-manager gspread beautifulsoup4 requests

      - name: Create credentials.json
        run: echo '${{ secrets.GSPREAD_CREDENTIALS }}' > credentials.json

      - name: Run Scraper
        env:
          SHARD_INDEX: 0
          SHARD_STEP: 20
          START_INDEX: 1
          END_INDEX: 2500
          CHECKPOINT_FILE: checkpoint_group1_0.txt
        run: python run_scraper.py

      - name: Commit and Push Checkpoint
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add checkpoint_group1_0.txt || echo "No checkpoint to update"
          git commit -m "Update scraper checkpoint" || exit 0
          git push
